// Imports
import type { EventInterface } from '@/interfaces/EventInterface.js';

// Seed Data
export const eventSeeder: EventInterface[] = [
  {
    id: 1,
    imageURL:
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80',
    title: 'Tech Innovation Summit 2026',
    description: 'Conference on artificial intelligence and modern web development.',
    type: 'Conference',
    category: 'Technology',
    date: '2026-09-15',
    time: '09:00 AM',
    duration: '8 hours',
    price: 120,
    status: 'Active',
    venueId: 1,
    ticketIds: [1, 3],
  },
  {
    id: 2,
    imageURL:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    title: 'AI & Cloud Computing Expo',
    description: 'Hands-on demonstrations and talks on next-gen cloud architectures.',
    type: 'Expo',
    category: 'Technology',
    date: '2026-11-10',
    time: '10:00 AM',
    duration: '6 hours',
    price: 75,
    status: 'Inactive',
    venueId: 1,
    ticketIds: [],
  },
  {
    id: 3,
    imageURL:
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    title: 'Indie Music Festival',
    description: 'Live band performances, urban art, and outdoor food stands.',
    type: 'Festival',
    category: 'Music',
    date: '2026-09-20',
    time: '04:00 PM',
    duration: '6 hours',
    price: 85,
    status: 'Active',
    venueId: 2,
    ticketIds: [2],
  },
  {
    id: 4,
    imageURL:
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    title: 'Classical Symphony Night',
    description: 'An evening of classical orchestral masterpieces in an acoustic venue.',
    type: 'Concert',
    category: 'Music',
    date: '2026-12-05',
    time: '07:30 PM',
    duration: '3 hours',
    price: 50,
    status: 'Inactive',
    venueId: 2,
    ticketIds: [],
  },
  {
    id: 5,
    imageURL:
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&auto=format&fit=crop&q=80',
    title: 'UI/UX Design Workshop',
    description: 'Learn to design attractive interfaces using Figma and modern tools.',
    type: 'Workshop',
    category: 'Design',
    date: '2026-10-05',
    time: '02:00 PM',
    duration: '3 hours',
    price: 65,
    status: 'Active',
    venueId: 3,
    ticketIds: [],
  },
  {
    id: 6,
    imageURL:
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&auto=format&fit=crop&q=80',
    title: 'Creative Branding & Motion Summit',
    description: 'Explore trends in motion design, visual identity, and brand strategy.',
    type: 'Seminar',
    category: 'Design',
    date: '2026-11-22',
    time: '11:00 AM',
    duration: '5 hours',
    price: 90,
    status: 'Inactive',
    venueId: 3,
    ticketIds: [],
  },
  {
    id: 7,
    imageURL:
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80',
    title: 'Global Gastronomy & Wine Fair',
    description: 'Tastings, live cooking sessions, and gourmet dishes from top chefs.',
    type: 'Fair',
    category: 'Gastronomy',
    date: '2026-10-18',
    time: '01:00 PM',
    duration: '7 hours',
    price: 110,
    status: 'Active',
    venueId: 1,
    ticketIds: [],
  },
  {
    id: 8,
    imageURL:
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    title: 'Artisan Coffee & Pastry Expo',
    description: 'Discover specialty coffees, barista championships, and baking masterclasses.',
    type: 'Expo',
    category: 'Gastronomy',
    date: '2026-11-30',
    time: '10:00 AM',
    duration: '4 hours',
    price: 40,
    status: 'Inactive',
    venueId: 2,
    ticketIds: [],
  },
  {
    id: 9,
    imageURL:
      'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&auto=format&fit=crop&q=80',
    title: 'City Marathon & Fitness Expo',
    description: 'Annual urban marathon featuring 5K, 10K, and 21K health runs.',
    type: 'Competition',
    category: 'Sports',
    date: '2026-10-25',
    time: '06:00 AM',
    duration: '6 hours',
    price: 45,
    status: 'Active',
    venueId: 1,
    ticketIds: [],
  },
  {
    id: 10,
    imageURL:
      'https://images.unsplash.com/photo-1517649763962-0c623266010b?w=600&auto=format&fit=crop&q=80',
    title: 'Urban Skate & Extreme Sports Championship',
    description: 'High-adrenaline skateboarding, BMX, and freestyle competitions.',
    type: 'Tournament',
    category: 'Sports',
    date: '2026-12-12',
    time: '02:00 PM',
    duration: '5 hours',
    price: 35,
    status: 'Inactive',
    venueId: 2,
    ticketIds: [],
  },
  {
    id: 11,
    imageURL:
      'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=600&auto=format&fit=crop&q=80',
    title: 'Modern Drama & Performing Arts Night',
    description: 'Contemporary theater plays and experimental stage performances.',
    type: 'Play',
    category: 'Theater',
    date: '2026-10-31',
    time: '08:00 PM',
    duration: '2 hours',
    price: 60,
    status: 'Active',
    venueId: 3,
    ticketIds: [],
  },
  {
    id: 12,
    imageURL:
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=600&auto=format&fit=crop&q=80',
    title: 'Classic Shakespeare Play Revival',
    description: 'A timeless dramatic production showcasing classic theater traditions.',
    type: 'Play',
    category: 'Theater',
    date: '2026-12-18',
    time: '07:00 PM',
    duration: '3 hours',
    price: 55,
    status: 'Inactive',
    venueId: 3,
    ticketIds: [],
  },
];
